[AZURE]
pat = AZURE_PERSONAL_ACCESS_TOKEN
; self_hosted_scm_url = OPTIONAL_AZURE_SELF_HOSTED_SCM_URL

tags = azure2cx, scm2cx

; CxOne project name format. Variables are $ORG, $PROJECT, and $REPOSITORY.
; For Azure DevOps, you should include the project in the name to avoid naming conflicts
; between repositories with the same name in different projects.
cxone_project_name_format = $ORG/$PROJECT/$REPOSITORY

; Organization inclusion
; include_orgs = org_1_regex, org_2_regex
; Project inclusion
; include_projects = project_1_regex, project_2_regex, project_3_regex
; Repository inclusion. Format is org_regex:repo_regex:branch_regex
; include_repos = org1:project1:repo1:branch1_regex, org2:project2:repo2:branch2_regex, org3:project3:repo3:branch3_regex

; Organization exclusion
; exclude_orgs = org_1_regex, org_2_regex
; Project exclusion
; exclude_projects = project_1_regex, project_2_regex, project_3_regex
; Repository exclusion. Pattern is org_regex:project_regex:repo_regex:branch_regex
; exclude_repos = org1:project1:repo1:branch1_regex, org2:project2:repo2:branch2_regex, org3:project3:repo3:branch3_regex


[GITHUB]
pat = GITHUB_PERSONAL_ACCESS_TOKEN
; self_hosted_scm_url = OPTIONAL_GITHUB_SELF_HOSTED_SCM_URL

tags = github2cx, scm2cx

; NOTE: CxOne project name format is NOT available for GitHub.
; The underlying CxOne API automatically uses the format $ORG/$REPOSITORY

; Organization inclusion
; include_orgs = org_1_regex, org_2_regex
; Repository inclusion. Format is org_regex:repo_regex:branch_regex
; include_repos = org1:repo1:branch1_regex, org2:repo2:branch2_regex, org3:repo3:branch3_regex

; Organization exclusion
; exclude_orgs = org_1_regex, org_2_regex
; Repository exclusion. Format is org_regex:repo_regex:branch_regex
; exclude_repos = org1:repo1:branch1_regex, org2:repo2:branch2_regex, org3:repo3:branch3_regex


[GITLAB]
pat = GITLAB_PERSONAL_ACCESS_TOKEN
; self_hosted_scm_url = OPTIONAL_GITLAB_SELF_HOSTED_SCM_URL

tags = gitlab2cx, scm2cx

; CxOne project name format. Variables available are $ORG and $REPOSITORY.
cxone_project_name_format = $ORG/$REPOSITORY

; Organization inclusion
; include_orgs = org_1_regex, org_2_regex
; Repository inclusion. Format is org_regex:repo_regex:branch_regex
; include_repos = org1:repo1:branch1_regex, org2:repo2:branch2_regex, org3:repo3:branch3_regex

; Organization exclusion
; exclude_orgs = org_1_regex, org_2_regex
; Repository exclusion. Format is org_regex:repo_regex:branch_regex
; exclude_repos = org1:repo1:branch1_regex, org2:repo2:branch2_regex, org3:repo3:branch3_regex



[BITBUCKET]
pat = BITBUCKET_PERSONAL_ACCESS_TOKEN
; self_hosted_scm_url = OPTIONAL_BITBUCKET_SELF_HOSTED_SCM_URL

tags = bitbucket2cx, scm2cx

; CxOne project name format. Variables available are $ORG, $PROJECT, and $REPOSITORY.
; For Bitbucket, you should include the project in the name to avoid naming conflicts
; between repositories with the same name in different projects.
cxone_project_name_format = $ORG/$PROJECT/$REPOSITORY

; Organization inclusion
; include_orgs = org_1_regex, org_2_regex
; Project inclusion
; include_projects = project_1_regex, project_2_regex, project_3_regex
; Repository inclusion. Format is org_regex:repo_regex:branch_regex
; include_repos = org1:project1:repo1:branch1_regex, org2:project2:repo2:branch2_regex, org3:project3:repo3:branch3_regex

; Organization exclusion
; exclude_orgs = org_1_regex, org_2_regex
; Project exclusion
; exclude_projects = project_1_regex, project_2_regex, project_3_regex
; Repository exclusion. Pattern is org_regex:project_regex:repo_regex:branch_regex
; exclude_repos = org1:project1:repo1:branch1_regex, org2:project2:repo2:branch2_regex, org3:project3:repo3:branch3_regex



[CX]
cx_iam_host = CXONE_IAM_HOST
cx_ast_host = CXONE_AST_HOST
cx_tenant = CXONE_TENANT
cx_api_key = CXONE_API_KEY